/* NEWSLETTER */
export const GET_NEWSLETTERS = "GET_NEWSLETTERS"
export const GET_NEWSLETTERS_SUCCESS = "GET_NEWSLETTERS_SUCCESS"
export const GET_NEWSLETTERS_FAIL = "GET_NEWSLETTERS_FAIL"


/**
 * Delete NEWSLETTER
 */
 export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER"
 export const DELETE_NEWSLETTER_SUCCESS = "DELETE_NEWSLETTER_SUCCESS"
 export const DELETE_NEWSLETTER_FAIL = "DELETE_NEWSLETTER_FAIL"