export const GET_ALL_PRODUCT_REVIEW = "GET_ALL_PRODUCT_REVIEW"
export const GET_ALL_PRODUCT_REVIEW_SUCCESS = "GET_ALL_PRODUCT_REVIEW_SUCCESS"
export const GET_ALL_PRODUCT_REVIEW_FAIL = "GET_ALL_PRODUCT_REVIEW_FAIL"
