export const GET_ALL_PRODUCT_REVIEW = "GET_ALL_PRODUCT_REVIEW"
export const GET_ALL_PRODUCT_REVIEW_SUCCESS = "GET_ALL_PRODUCT_REVIEW_SUCCESS"
export const GET_ALL_PRODUCT_REVIEW_FAIL = "GET_ALL_PRODUCT_REVIEW_FAIL"

export const ADD_PRODUCT_REVIEW = "ADD_PRODUCT_REVIEW"
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS"
export const ADD_PRODUCT_REVIEW_FAIL = "ADD_PRODUCT_REVIEW_FAIL"

export const UPDATE_PRODUCT_REVIEW = "UPDATE_PRODUCT_REVIEW"
export const UPDATE_PRODUCT_REVIEW_SUCCESS = "UPDATE_PRODUCT_REVIEW_SUCCESS"
export const UPDATE_PRODUCT_REVIEW_FAIL = "UPDATE_PRODUCT_REVIEW_FAIL"

export const DELETE_PRODUCT_REVIEW = "DELETE_PRODUCT_REVIEW"
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS"
export const DELETE_PRODUCT_REVIEW_FAIL = "DELETE_PRODUCT_REVIEW_FAIL"
