export const GET_ALL_PRODUCT_SIZE = "GET_ALL_PRODUCT_SIZE"
export const GET_ALL_PRODUCT_SIZE_SUCCESS = "GET_ALL_PRODUCT_SIZE_SUCCESS"
export const GET_ALL_PRODUCT_SIZE_FAIL = "GET_ALL_PRODUCT_SIZE_FAIL"
