export const GET_ALL_PRODUCT_IMAGE = "GET_ALL_PRODUCT_IMAGE"
export const GET_ALL_PRODUCT_IMAGE_SUCCESS = "GET_ALL_PRODUCT_IMAGE_SUCCESS"
export const GET_ALL_PRODUCT_IMAGE_FAIL = "GET_ALL_PRODUCT_IMAGE_FAIL"

export const GET_BY_ID_PRODUCT_IMAGE = "GET_BY_ID_PRODUCT_IMAGE"
export const GET_BY_ID_PRODUCT_IMAGE_SUCCESS = "GET_BY_ID_PRODUCT_IMAGE_SUCCESS"
export const GET_BY_ID_PRODUCT_IMAGE_FAIL = "GET_BY_ID_PRODUCT_IMAGE_FAIL"